sudo: required
services:
  - docker

before_install:
  - docker build -t chandanchaudhary/docker-react -f Dockerfile.dev .

script:
  - docker run chandanchaudhary/docker-react npm run test -- --coverage
